master:
  image: docker.iwanna.xyz:5000/hmonkey/mpi:v1
  command: /usr/sbin/sshd -D
  container_name: master
  links:
    - slave1
    - slave2
  environment:
    - hello: 'nju'
slave1:
  image: docker.iwanna.xyz:5000/hmonkey/mpi:v1
  command: /usr/sbin/sshd -D
  container_name: slave1
slave2:
  image: docker.iwanna.xyz:5000/hmonkey/mpi:v1
  command: /usr/sbin/sshd -D
  container_name: slave2
