master:
  image: docker.iwanna.xyz:5000/hmonkey/mpi:v1
  command: /bin/bash -c "service ssh start"
  container_name: master
  links:
    - slave1
    - slave2
  environment:
    - hello='nju'
slave1:
  image: docker.iwanna.xyz:5000/hmonkey/mpi:v1
  command: /bin/bash -c "service ssh start"
  container_name: slave1
slave2:
  image: docker.iwanna.xyz:5000/hmonkey/mpi:v1
  command: /bin/bash -c "service ssh start"
  container_name: slave2
